practice-app/translate/urls.py
from django.urls import path

from . import views

app_name = 'translate'
urlpatterns = [
    path('', views.post_helper, name='index'),
    path('<slug:from_lang_code>/', views.translator, name='from'),
    path('-/<slug:to_lang_code>/', views.translator, name='to'),
    path('<slug:from_lang_code>/<slug:to_lang_code>/', views.translator, name='from-to')


    # path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # path('<int:question_id>/vote/', views.vote, name='vote'),
]

practice-app/translate/models.py
from django.db import models

from django.conf import settings
import requests, uuid, json


# Create your models here.
class Language(models.Model):
    name = models.CharField(max_length=40)
    code = models.CharField(max_length=2)

    def __str__(self):
        return "{} ({})".format(self.name, self.code)

    def __eq__(self, other):
        return self and other and self.code == other.code

    def toJSON(self):
        return self.code

    def translate(self, from_language, text):
        url = "https://api.cognitive.microsofttranslator.com/translate?api-version=3.0&textType=plain&to={}&from={}" \
            .format(self.code, from_language.code)
        headers = {
            'Ocp-Apim-Subscription-Key': settings.AZURE_TRANSLATOR_API_KEY,
            'Ocp-Apim-Subscription-Region': settings.AZURE_TRANSLATOR_REGION,
            'Content-type': 'application/json',
            'X-ClientTraceId': str(uuid.uuid4())
        }
        request = requests.post(url, headers=headers, json=[{"text": text}])
        response = request.json()
        return response[0]["translations"][0]["text"]
        # https://docs.microsoft.com/en-us/azure/cognitive-services/translator/quickstart-python-translate

practice-app/translate/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

import json

from .models import Language
from .serializers import CustomJSONEncoder


@csrf_exempt
def post_helper(request):
    if request.method == "POST":
        if request.content_type == 'application/json':
            request.POST = json.loads(request.body)
    return translator(
        request,
        from_lang_code=request.POST.get('from', None),
        to_lang_code=request.POST.get('to', None)
    )


def translator(request, from_lang_code=None, to_lang_code=None):
    status = 200
    context = {
        "errors": [],
        "from": None,
        "to": None,
        "source": None,
        "translation": None
    }
    if from_lang_code:
        try:
            context["from"] = Language.objects.get(code=from_lang_code)
        except Language.DoesNotExist:
            context["errors"].append(
                "No language for code, {}, exists. Defaulting from language to empty."
                .format(from_lang_code)
            )
    if to_lang_code:
        try:
            context["to"] = Language.objects.get(code=to_lang_code)
        except Language.DoesNotExist:
            context["errors"].append(
                "No language for code, {}, exists. Defaulting to language to empty."
                .format(to_lang_code)
            )
    if request.method == "POST":
        context["source"] = request.POST.get('source', None)
        if not context["from"]:
            context["errors"].append(
                "Please select a language to translate from."
            )
        if not context["to"]:
            context["errors"].append(
                "Please select a language to translate to."
            )
        if context["from"] and context["from"] == context["to"]:
            context["errors"].append(
                "From language & To language parts cannot be the same."
            )
        if not context["source"]:
            context["errors"].append(
                "Please enter a text to translate."
            )
        if len(context["errors"]) == 0:
            try:
                context["translation"] = context["to"].translate(
                    from_language=context["from"],
                    text=context["source"]
                )
            except:
                context["errors"].append(
                    "Failed to translate the text for some unknown reason. \
                    Maybe try again later or contact the developer."
                )
                status = 500
        else:
            status = 400
    if request.content_type == 'application/json':
        return JsonResponse(context, encoder=CustomJSONEncoder, status=status)
    else:
        context["languages"] = Language.objects.all()
        return render(request, 'translate/translator.html', context, status=status)

practice-app/translate/templates/translate/translator.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Text Translator</title>
    {% load static %}

    <link rel="stylesheet" type="text/css"
          href="{% static 'translate/style.css' %}"/>
</head>
<body>
<h1>
    Text Translator
</h1>
{% for error in errors %}
    <p class="error">
        <strong>
            {{ error }}
        </strong>
    </p>
{% endfor %}
<form id="translate_form" action="{% url 'translate:index' %}" method="post">
    {%  csrf_token %}
    <label for="from">From Language:</label>
    <select id="from" name="from">
        <option disabled {% if not from %} selected{% endif %}>
            Select Language
        </option>
        {% for language in languages %}
            <option value="{{ language.code }}"
                    {% if from == language %} selected {% endif %}>
                {{ language.name }}
            </option>
        {% endfor %}
    </select>
    <label for="to">To Language:</label>
    <select id="to" name="to">
        <option disabled {% if not to %} selected{% endif %}>
            Select Language
        </option>
        {% for language in languages %}
            <option value="{{ language.code }}"
                    {% if to == language %} selected {% endif %}>
                {{ language.name }}
            </option>
        {% endfor %}
    </select>
    <textarea form="translate_form" id="source" name="source" placeholder="Enter the text to translate."
        >{% if source %}{{ source }}{% endif %}</textarea>
    <input type="submit"/>
</form>

{% if translation %}
    <div class="translation">
        <p>
            {{ translation }}
        </p>
    </div>
{% endif %}

</body>
</html>